### ISSUE TITLE
Assignment 1: Identify tasks to be done and create a backlog on the project board

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#100]
The first assignment requires us to go over all the planning we have done last semester and to review, update and elaborate on them. This includes our [requirements](https://github.com/bounswe/2021SpringGroup4/wiki/Software-Requirements-Specification-(SRS)), diagrams and mock-ups which are ready available in the wiki. Also of importance is the refinement of the [project plan](https://github.com/bounswe/2021SpringGroup4/wiki/Project-Plan) and the [responsibility assignment matrix](https://github.com/bounswe/2021SpringGroup4/wiki/Responsibility-Assignment-Matrix-(RAM)). I will be identifying these subtasks and posting them on our [project board](https://github.com/bounswe/2021SpringGroup4/projects/2) so that everyone can go over them and provide feedback/propose changes in these documents.

**Deadline**: 14/10/2021

**Comment by FatihAkgoz** [comment]
Backlog is created and in use. Reviews has been made on our requirements.
