### ISSUE TITLE
Assignment 1 : Revise Project Plan and Responsibility Matrix (RAM)

### ISSUE THREAD

**Issue by yigitsarioglu** [bounswe/2021SpringGroup4#101]
The project plan and responsibility matrix(RAM) will be revised according to new group members and changes in our timeline.
Deadline : 15/10/2021

**Comment by yagmurse** [comment]
I am sorry for missing the deadline. I updated project plan but having issues about uploading files from Project Libre. I am working on it with Yiğit. It will be updated by tomorrow.
