### ISSUE TITLE
Assignment 1 : Revise Mockups & Scenarios according to changes in Requirements

### ISSUE THREAD

**Issue by yigitsarioglu** [bounswe/2021SpringGroup4#106]
Should revise mockups & scenarios according to changes in Software Requirements. 
Changes can be tracked [here ](https://github.com/bounswe/2021SpringGroup4/issues/103#issue-1023763182)
Since we do not know the changes, I assigned all group members to this issue.

**Comment by FatihAkgoz** [comment]
Since software requirements were checked and approved by the team, currently no changes are made.
