### ISSUE TITLE
Frontend : Inital downloads and setups for React

### ISSUE THREAD

**Issue by yigitsarioglu** [bounswe/2021SpringGroup4#118]
React installation requires nodejs installation on the computer. Here is the [link](https://nodejs.org/en/)
React project files need to be installed locally
I will also use vscode as the code editor, it will also be installed.

**Comment by yagmurse** [comment]
I created the ReactProjects and completed installation of necessary tools on my computer

**Comment by yagmurse** [comment]
I created  and run the ReactProjects, also completed installation of necessary tools on my computer.

**Comment by yagmurse** [comment]
I created  and run the ReactProjects, also completed installation of necessary tools on my computer.
