### ISSUE TITLE
Backend: Develop profile api and authentication api

### ISSUE THREAD

**Issue by mehmethilmidundar** [bounswe/2021SpringGroup4#119]
In backend-main/code/backend/api authentication api and profile api should be developed according to project requirements. These apis should satisfy backend profile functionalities.

Planned due time:31/10/2021

- [x] Finish tutorail about django rest framework.
- [x] Install necessary programs on local.

**Comment by FatihAkgoz** [comment]
What is the situation in the 3rd task? Since Tolga is also developing the authentication api I think we should remove the third task and close this issue.

**Comment by mehmethilmidundar** [comment]
Thanks for feedback. I misunderstood.
