### ISSUE TITLE
Frontend Meeting for final trials before the first client presentation

### ISSUE THREAD

**Issue by yagmurse** [bounswe/2021SpringGroup4#146]
We need to look again at the recent changes to the Registration and Event Creation Pages and our backend connection status. Finally, it will be examined whether the site is fully functional for presentation.

Time and Date: 22.00 , 15 Nov 2021 
place: Google Meet 

Link will be sent to the frontend Whatsapp grup

**Comment by yigitsarioglu** [comment]
The customer meeting will be at 13:00 on Tuesday(16-11-2021). we gathered as a frontend team to review what we've done for the last time.

**Comment by yigitsarioglu** [comment]
Our meeting went very well, we put the finishing touches. we are ready for customer meeting. so ı am closing this issue.
