### ISSUE TITLE
2nd meeting on Zoom

### ISSUE THREAD

**Issue by yigitsarioglu** [bounswe/2021SpringGroup4#16]
We will meet at 21.30 on Tuesday. ( 30.03.2021 - 21.30  , Platform : Zoom )
Links will be shared.  

**Participitants**
- [x] Salih Furkan
- [x] Ece Dilara Aslan
- [x] İhsan Mert Atalay
- [x] Muhammed İrfan Bozkurt
- [x] Mehmet Hilmi Dündar
- [x] Berkay Gümüş
- [x] Tolga Kerimoğlu
- [x] Yiğit Sarıoğlu
- [x] Yağmur Selek

**Comment by kerimoglutolga** [comment]
Everyone has attended.
