### ISSUE TITLE
Frontend Team Meeting : Planning and Distribution of Tasks

### ISSUE THREAD

**Issue by yigitsarioglu** [bounswe/2021SpringGroup4#164]
A meeting will be held on 30 November 2021 at 22:00.

-What will be done, deficiencies will be determined
-Weekly assignments for team members will be determined.

**Comment by yagmurse** [comment]
We had the meeting and I am now responsible with changing the design of the our website and implementing the map function.

**Comment by yigitsarioglu** [comment]
We have completed our meeting and i will do user profile creation(update), view and photo upload features.
