### ISSUE TITLE
Frontend Meeting : Weekly Ordinary Meeting & Preparing for Customer Demo

### ISSUE THREAD

**Issue by yigitsarioglu** [bounswe/2021SpringGroup4#178]
A meeting will be held on 09 December 2021 (09/12/2021) at 18:30.
Participants : Frontend team ( Yiğit Sarıoğlu, Yağmur Selek, Ali Alperen Durak) 

Our task: The customer demo will be held next week. Preliminary preparations and plans are needed for this.

- User Profile Page & Photo Upload Features
- Image/Photo upload to cloud service
- Google Map API
- Google Geocode API    ( find user's location from browser)
- Google Autocomplete Functionality
- Dockerize and Deploy

**Comment by yagmurse** [comment]
Everyone participated in meeting and I am responsible with Google Autocomplete Functionality

**Comment by alialperendurak** [comment]
All of the tasks are completed by the team and performed in the Customer Presentation
