### ISSUE TITLE
Carry GitHub repository research into a single page

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#18]
Carry your individual research into the main summary page and delete your old page.

**Comment by salihfurqan** [comment]
everyone should move their page and append their text to the [link](https://github.com/bounswe/2021SpringGroup4/wiki/Favorite-Repositories) here, then delete their own pages please

**Comment by kerimoglutolga** [comment]
This has been completed. The single page containing the repository research can be found [here](https://github.com/bounswe/2021SpringGroup4/wiki/Favorite-Repositories).
