### ISSUE TITLE
Frontend : Implement Autofill functionality to google maps; Maps.js  Component in frontend

### ISSUE THREAD

**Issue by yagmurse** [bounswe/2021SpringGroup4#183]
Users should be able to select a place from google maps by typing the name of the location. Location suggestion will be taken from Places Api. As they select a suggested place Latitude and Longitude values will be in the center of the map.

**Comment by alialperendurak** [comment]
Autofill functionality is implemented in the **Maps.js** component. **PlacesAutocomplete** from **"react-places-autocomplete"** is used for the functionality.  It is live for **Events** and **Create Event** page. Also, the functionality was performed in Customer Presentation 2.
