### ISSUE TITLE
Create a wiki page for newcomers

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#19]

**Comment by yagmurse** [comment]
https://github.com/bounswe/2021SpringGroup4/wiki/A-warm-welcome-to-our-new-teammates-!

**Comment by yagmurse** [comment]
I created a welcome page for our new members. https://github.com/bounswe/2021SpringGroup4/wiki/A-warm-welcome-to-our-new-teammates-!
