### ISSUE TITLE
Frontend: Add Map Functionality for Location Selection on Event Create Page 

### ISSUE THREAD

**Issue by yagmurse** [bounswe/2021SpringGroup4#190]
Google Maps will be added to the Event Creation Page. Users should be able to select location from map. A marker should be placed on the clicked place;  latitude and longitude values and address should be sent to the Backend api events endpoint

**Comment by yigitsarioglu** [comment]
We gathered as a frontend team on Sunday and Monday (12-13 December 2021) and implemented the map functions. (previously, I created a google developer console account and got an API key)

**Comment by yigitsarioglu** [comment]
When users create an Event;
-Users could select a place by clicking on the map
-Latitude and Longitude values of the adress is kept as a variable and sent to the backend
-One of the address (from the ten ) values returned from google map is selected and sent to the backend

**Comment by yagmurse** [comment]
Add Map Functionality for Location Selection on Event Create Page is completed and it is presented to Customer
