### ISSUE TITLE
Identify the user requirements

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#27]
Identify the user requirements for the project and document them in the SRS template in wiki.

**Comment by salihfurqan** [comment]
included in the SRS page after some discussion

**Comment by salihfurqan** [comment]
user req numbered 3.1.1.2.3 partitioned into two and changed according to info gathered from the customer meeting #1

**Comment by salihfurqan** [comment]
requirement removed from the requirements: 3.1.1.1.2 User shall be able to include his/her social media accounts for sign-in alternatives during sign-up or afterwards.

**Comment by salihfurqan** [comment]
requirement added: 3.1.1.6.3 User shall be able to create equipment sale posts that include its description.
