### ISSUE TITLE
Identify and document the system requirements

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#28]
Identify and document the system requirements in the wiki.

**Comment by kerimoglutolga** [comment]
Closing this issue. The documented requirements can be found in the SRS file in our wiki.

**Comment by salihfurqan** [comment]
3.1.2.3.9 changed according to info gathered from the customer meeting #1

**Comment by kerimoglutolga** [comment]
Removed the following:

-  **3.1.2.3.9** The system shall allow users to apply to events even if they are full.
