### ISSUE TITLE
Identify and document the non-functional requirements

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#29]
Identify and document the non-functional requirements in the wiki.

**Comment by irfanbozkurt** [comment]
1. In the case when the non-functional requirements are not met the basic functionality will not be impacted. (It's not mandatory to meet these requirements)
2. Non-functional requirements when defined and executed well will help to make the system easy to use and enhance the performance.
3. Non-functional requirements focus on user expectations, as they are product properties. 


Basic ideas on the most common non-functional requirements:

**Usability**
This focuses on the appearance of the user interface and how people interact with it. What colour are the screens? How big are the buttons?

Reliability / Availability. What are the uptime requirements? Does it need to function 24/7/365?

**Scalability**
As needs grow, can the system handle it? For physical installations, this includes spare hardware or space to install it in the future.

**Performance**
How fast does it need to operate?

**Supportability**
Is support provided in-house or is remote accessibility for external resources required?

**Security**
What are the security requirements, both for the physical installation and from a cyber perspective?

**Comment by irfanbozkurt** [comment]
Closing the issue upon completion, suggesting a walkthrough it in the closest meeting.

**Comment by irfanbozkurt** [comment]
Reopening issue to formally represent the need for a walkthrough.

**Comment by yagmurse** [comment]
This issue is completed. The non functional requirements can be found in the SRS file in our wiki.
