### ISSUE TITLE
Give feedback on the Software Requirements Specification

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#30]
This is an issue for our TA to give feedback on the initial draft of our SRS document that can be viewed [**here**](https://github.com/bounswe/2021SpringGroup4/wiki/Software-Requirements-Specification-(SRS)).
We are open to any feedback, more details the better.

**Comment by yigitsarioglu** [comment]
Feedback received.. this issue will opened again if necessary..
