### ISSUE TITLE
Scenario 1: Create the user scenario on finding and joining an event

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#31]
Create the user scenario on finding and joining an event and document it on wiki.

**Comment by irfanbozkurt** [comment]
Had a meeting with Yağmur and Berkay, creating the scenario according to new customizations. Our documentation of this scenario is [here](https://github.com/bounswe/2021SpringGroup4/wiki/Scenario-1).

**Comment by irfanbozkurt** [comment]
Added guest-user requirements to the SRS page.

**Comment by yagmurse** [comment]
We completed our scenario https://github.com/bounswe/2021SpringGroup4/wiki/Scenario-1
