### ISSUE TITLE
Scenario 2: Create user scenario on creating and organizing an event

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#32]
Create user scenario on creating and organizing an event document it on the wiki.

**Comment by eceasslan** [comment]
Had a Zoom meeting with Tolga and Mert, and we created a scenario of a user who wants to create a soccer event. Our documentation of this scenario is [here](https://github.com/bounswe/2021SpringGroup4/wiki/Scenario-2)

**Comment by kerimoglutolga** [comment]
Scenario 2 is completed as a draft. We moved on to creating the mockup. Our progress on the mockup can be followed in this issue: (https://github.com/bounswe/2021SpringGroup4/issues/35)

**Comment by kerimoglutolga** [comment]
Scenario 2 is completed as a draft. We moved on to creating the mockup. Our progress on the mockup can be followed at the issue: (https://github.com/bounswe/2021SpringGroup4/issues/35)

**Comment by kerimoglutolga** [comment]
Removed the following acceptance criteria:

-  **3.1.2.3.9** The system shall not allow users to apply to full events.

**Comment by kerimoglutolga** [comment]
We have made small changes on the story, acceptance criteria and actions to apply to both Web and Android mockups.
