### ISSUE TITLE
Scenario 3: Create the user scenario on finding equipment for a sport

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#33]
Create the user scenario on finding equipment for a sport and document it in the wiki.

**Comment by yigitsarioglu** [comment]
we have created scenario 3 (finding equipment for a sport) and documented it in the [wiki page](https://github.com/bounswe/2021SpringGroup4/wiki/Scenario-3)

**Comment by salihfurqan** [comment]
done, documented on the link in the previous comment
