### ISSUE TITLE
Create mockup for scenario 2 on creating and organizing an event 

### ISSUE THREAD

**Issue by eceasslan** [bounswe/2021SpringGroup4#35]
Create mockup for scenario 2 and document it on [here](https://github.com/bounswe/2021SpringGroup4/wiki/Scenario-2).

**Comment by kerimoglutolga** [comment]
We have created the persona, determined the goals, actions and the acceptance criteria. Final version can be found on the specified link.

**Comment by eceasslan** [comment]
Created a website mockup via Pencil Project in a Zoom meeting with @kerimoglutolga and @trewwert5656.

**Comment by eceasslan** [comment]
After having a meeting with TA, we need to make some changes on homepage and event creation page, also we need to create an Android mockup.

**Comment by kerimoglutolga** [comment]
We have created the Android Mockup and made the changes to the event creation page and the profile page for the Web mockup.
Updated version can be found [here](https://github.com/bounswe/2021SpringGroup4/wiki/Scenario-2).
