### ISSUE TITLE
Create mockup for scenario 3 on finding equipment for a sport

### ISSUE THREAD

**Issue by eceasslan** [bounswe/2021SpringGroup4#36]
Create mockup for scenario 3 and document it on [here](https://github.com/bounswe/2021SpringGroup4/wiki/Scenario-3).

**Comment by salihfurqan** [comment]
done, documented [here](https://github.com/bounswe/2021SpringGroup4/wiki/Scenario-3)

**Comment by yigitsarioglu** [comment]
After customer meeting , we have new ideas and plans so we should review our work. 

-  We have done only web-page mockup, we should do also for android.

- Users shall be able to create equipment posts. These posts includes information about equipment and who is seller.

- The location can be selected from the map or or the location name will be written.

- Badges can also be given to sellers. (this is optional)

**Comment by salihfurqan** [comment]
Android mockups were done by @yigitsarioglu and uploaded to the repo. Documentation is remaining to be done by the assignee group.

**Comment by salihfurqan** [comment]
Web mockups and also android ones were updated by @yigitsarioglu and uploaded to the repo and the wiki. I updated the acceptance criteria according to the updated user requirements. Issue is completed for now.
