### ISSUE TITLE
Create Sequence Diagrams for various functionalities and document them on wiki

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#39]
Create sequence diagrams for various functionalities of the application and document them on wiki.

**Comment by eceasslan** [comment]
We are going to create Sequence Diagrams after Class Diagram is ready, in order to be consistent.

**Comment by kerimoglutolga** [comment]
After long hours, we (@kerimoglutolga, @eceasslan, @trewwert5656) have created the Sequence Diagrams for all key use cases:
- Registration
- Login
- Create Event
- Join Event
- Search Event
- Create Equipment Post
- Comment on Equipment
- Give Badge to Another Player

Diagrams can be found [here](https://github.com/bounswe/2021SpringGroup4/wiki/Sequence-Diagrams)

**Comment by eceasslan** [comment]
We will schedule a meeting with our TA in order to revise what we have done and receive some feedbacks.

**Comment by kerimoglutolga** [comment]
We have received extensive feedback from our TA and will be updating the diagrams accordingly.

- Most notably, we will remove the UI modules and try to incorporate the user module instead.
- Additionally we will be splitting the diagram of applying to an event into seperate diagrams and we will show the flow of an event creator accepting a user seperately.

**Comment by kerimoglutolga** [comment]
> We have received extensive feedback from our TA and will be updating the diagrams accordingly.
> 
> * Most notably, we will remove the UI modules and try to incorporate the user module instead.
> * Additionally we will be splitting the diagram of applying to an event into seperate diagrams and we will show the flow of an event creator accepting a user seperately.

We (@kerimoglutolga, @eceasslan, @ihsanmertatalay) have updated all the diagrams according to the feedback from the TA.
Updated versions can be found [here](https://github.com/bounswe/2021SpringGroup4/wiki/Sequence-Diagrams).
