### ISSUE TITLE
Create a Use Case Diagram that shows the interaction between users and the functionality

### ISSUE THREAD

**Issue by yigitsarioglu** [bounswe/2021SpringGroup4#40]
We should create a Use Case Diagram that shows the interaction between users and the functionality, and we should document it on wiki.

**Comment by mehmethilmidundar** [comment]
We arranged a meeting at 2.30 pm to create use case diagram with @salihfurqan and @yigitsarioglu.

**Comment by salihfurqan** [comment]
We had a meeting with @mehmethilmidundar, @salihfurqan and @yigitsarioglu for 2 hours for the diagram.
We looked at previous use case diagrams for ideas. We used lucidchart, and the final document is [here](https://lucid.app/lucidchart/859a7db2-767a-4eac-9ec5-0601eadfc27f/view?invitationId=inv_474ecbff-8238-4b6f-b0d0-a60e4f3ac337&page=.Q4MUjXso07N#).
I uploaded the final png to the repo.

**Comment by yigitsarioglu** [comment]
After the meeting, we add our use case diagram to our repo and I created a wiki page [here](https://github.com/bounswe/2021SpringGroup4/wiki/Use-Case-Diagram)

**Comment by salihfurqan** [comment]
The current version of the [diagram](https://github.com/bounswe/2021SpringGroup4/wiki/Use-Case-Diagram) should be reviewed by other team members and assistants.

**Comment by yigitsarioglu** [comment]
We have received extensive feedback from our TA and we have to update the use case diagrams accordingly.

**Comment by mehmethilmidundar** [comment]
We had a meeting to update our diagram according to feedbacks of our teaching assistant with @salihfurqan, @yigitsarioglu,and @mehmethilmidundar at 6 may 21.00.

**Comment by salihfurqan** [comment]
I have updated the use case diagram in our repo and our wiki accordingly. We will show the new diagram in the next customer meeting to our TA.

**Comment by salihfurqan** [comment]
We showed the diagram to our TA in a meeting on 7 May and received an approval, so the diagram is completed and can be seen [here](https://github.com/bounswe/2021SpringGroup4/wiki/Use-Case-Diagram).
