### ISSUE TITLE
Create a Class Diagram, identify classes and relationships between them and document them on wiki 

### ISSUE THREAD

**Issue by yagmurse** [bounswe/2021SpringGroup4#41]
Amateur Sports Coordination Platform Project - Class Diagram 

In order to make Sequence Diagrams more accurate, the general lines of the Class Diagram should be completed today. 

1) Identify Classes , their parameters, functions (with return types and arguments)
2) Relationship between classes

**Comment by irfanbozkurt** [comment]
After a 30-min meeting with @everybody at noon, we started working on it at around 15.00 with @yagmurse and @berkaygumus. 

I created the first template considering our requirements and other projects. Then all together, we focused on different aspects like what functions classes should have & what kinds of relationships shoud exist.

We uploaded the final PNG to the repo & created the [Class Diagram](https://github.com/bounswe/2021SpringGroup4/wiki/Class-Diagram) wiki page.

The current version of the diagram must be reviewed by other team members.

**Comment by yagmurse** [comment]
We are going to update our class diagram according to our assistant's - @emrebil -  feedback. We are trying to find us a common available time right now.

**Comment by irfanbozkurt** [comment]
W.r.t the e-mail feedback I received from the assistant, I made the following changes on the class diagram:

- Field _e-mail_ of class **User** changed to public & the only private field left is now the _password_. The system is responsible for getting the password from the database to verify the entered information.
- method _modifyEvent(Dictionary)_ added to class **Event**.
- _adjustPrivacySettings(int)_ & _adjustNotificationSettings(int)_ methods of class **User** had no fields to save the settings. Added two int fields _notificationPreferences_ and _privacyPreferences_, to represent each preference with a bit.
- created a class named **AnalyticsEngine** which seperates the analytics issue from the general picture, to provide ease for implementation.
- added field _applicants[]_ for the class **Event** to represent applicants for the creator to choose from.
- method _sendNotification()_ moved to the class **Notificator**, and added field _type_ (enum) to represent the type of the notification to be sent.
- Method _receiveNotifications()_ added to the class **User**, imagining a message system with the class **Notificator**. Added an additional field _notifications[]_ to gather these notifications in.
  This function may consider the notification settings of the user to eliminate some of the incoming messages from the class **Notificator**.
