### ISSUE TITLE
Find a Name For Our Project

### ISSUE THREAD

**Issue by yigitsarioglu** [bounswe/2021SpringGroup4#43]
I think, it's time for us to find a name for our application and website.. Please write your name options.

**Comment by yigitsarioglu** [comment]
my suggesitons are Champion, play&meet, PlayFinder, Arena

**Comment by ihsanmertatalay** [comment]
There are other ideas teammate, team-up,be-team,lets-team,sports mate,platoon

**Comment by salihfurqan** [comment]
I don't currently have an idea on the name but I would like to say I like 'PlayFinder'.

**Comment by yigitsarioglu** [comment]
my other sugestions are  "Amadeus" , "PlayTicket" , "Eventicket" , "Player" .

**Comment by FatihAkgoz** [comment]
We have decided on the name SportsHub at the lab session at 26.10.2021
