### ISSUE TITLE
Milestone Report 1: Summary of Work Done By Each Group Member

### ISSUE THREAD

**Issue by yigitsarioglu** [bounswe/2021SpringGroup4#44]
We should write summary of our works to the first milestone report. Please write your own work summary to our slack channel. #summary-work-done

**Comment by salihfurqan** [comment]
I added the very brief summary of my work to the report on 7 May.

**Comment by berkaygumus** [comment]
I wrote the summary of my works to the report.

**Comment by kerimoglutolga** [comment]
I've added my summary to the report.

**Comment by irfanbozkurt** [comment]
My summary added.

**Comment by ihsanmertatalay** [comment]
My summary added to the milestone report.

**Comment by eceasslan** [comment]
Added my work summary to the Milestone report 1.
