### ISSUE TITLE
Milestone Report 1: Create the project plan and add it to the wiki

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#45]
Create the project plan and document it on its own page in the wiki.

**Comment by berkaygumus** [comment]
After the meeting with @yagmurse and @irfanbozkurt, we completed the first version of the project plan for cmpe352

**Comment by irfanbozkurt** [comment]
I have been more like a reviewer as I've dealth with changes w.r.t assistant's feedback. We wanted minimum flows in the milestone report.

**Comment by kerimoglutolga** [comment]
I have added the project plan to the wiki and the sidebar.

**Comment by kerimoglutolga** [comment]
I have added the project plan to the wiki and the sidebar.
