### ISSUE TITLE
Milestone Report 1: Set up the layout and design

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#50]
Set up the overall structure, layout and design of the report. Also link the contents list to their corresponding sections in the report.

**Comment by kerimoglutolga** [comment]
I have designed the timeline graphic that displays where we are in the project and the past work in a concise manner and added it to the report.

**Comment by salihfurqan** [comment]
I added and laid out the mockups with their scenarios, the requirements with the glossary, the 'summary of work done individually' table and the table of contents to the report on 2 May.

**Comment by yigitsarioglu** [comment]
I added and designed/updated the communication plan, list and status of deliverable table  to the report on 2 May.

**Comment by eceasslan** [comment]
Added class diagram, updated contents, organized and designed page layout.

**Comment by kerimoglutolga** [comment]
Added the project and plan the RAM to the wiki, fixed the design and finalized the report. The report can now be found on the wiki.
