### ISSUE TITLE
Untidy gaps in the Milestone report

### ISSUE THREAD

**Issue by irfanbozkurt** [bounswe/2021SpringGroup4#52]
We had an irregular spacing in the milestone report as we preferred Google Docs, and it seems not to be fully compatible with Microsoft Word. 
We had to download the Google Doc as .docx and convert to PDF later to ensure we can compress our report under 2MB. 
However, general aesthetics of the report got affected and I suggest we correct these defects by hand, manually going through the .docx file.

But the general picture is clear though, this is not an issue demandig a change in the content.

**Comment by yigitsarioglu** [comment]
it's been a long time since we delivered the project/milestone report. And we solve this problem by correct defects by hand. So I close this issue.
