### ISSUE TITLE
Implementation Assignment: API Documentation

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#74]
Everyone should document their API in the API-docs.md file inside the practice-app folder.

**Comment by kerimoglutolga** [comment]
I have created a template for API documentation and documented the two APIs i have created [here]. (https://github.com/bounswe/2021SpringGroup4/blob/dev/practice-app/API-docs.md) 
You can use the same syntax for documenting your own API.

**Comment by berkaygumus** [comment]
I added the documentation of NBA team API to the API-docs.md file in dev branch.

**Comment by yagmurse** [comment]
I have documented my Create Event Post API in the API-docs.md file inside the practice-app folder. I created a request to commit my changes, because I am not sure about urls. Please check them before merge.

**Comment by ihsanmertatalay** [comment]
I added my document which about weather condution of Istanbul

**Comment by eceasslan** [comment]
I have written Formula 1 API documentation in API-docs.md file.

**Comment by mehmethilmidundar** [comment]
I have also added my documentation for holidays api to API-docs.md .

**Comment by salihfurqan** [comment]
I added my documentation of the 'random_article' and the 'eq_post' APIs to the md file.

**Comment by yigitsarioglu** [comment]
Since everyone in the group has uploaded it ,I close this issue.
