### ISSUE TITLE
Milestone Report 2: Summary Of Work Done

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#82]
Everyone should write the summary of work they have done in the Milestone Report on the shared Google Docs file.

- [X]  Tolga Kerimoğlu

**Comment by yigitsarioglu** [comment]
I wrote my summary of work I have done . Then I added this to the report on the shared Google Docs file.
- [X]  Yiğit Sarıoğlu

**Comment by berkaygumus** [comment]
I added my summary of work to the shared Google Docs file.

**Comment by ihsanmertatalay** [comment]
ı wrote summary of the my work

**Comment by irfanbozkurt** [comment]
Added my contributions & documentations to the Google Docs file.

**Comment by salihfurqan** [comment]
I added my summary of work on the shared google docs file.

**Comment by eceasslan** [comment]
Added my summary of work done to the Google Docs.

**Comment by mehmethilmidundar** [comment]
I 've also added my summary for work to the shared Google Document.

**Comment by yagmurse** [comment]
I  also added my summary of work on the shared google docs file.
